#!/usr/bin/env bash
set -euo pipefail

POSE_MODEL="${POSE_MODEL:-yolo11l-pose.pt}"

usage() {
  echo "Usage: $0 [--pose] <video.mp4> [yolo_model.pt]"
  echo "Example: $0 --pose video.mp4"
  echo
  echo "Environment overrides:"
  echo "  POSE_MODEL=path        path to the pose model (default: ${POSE_MODEL})"
  echo "  PROJECT, NAME, OUT, BATCH, DEVICE, COORDS as before"
}

POSE=false
while [[ $# -gt 0 && "${1:-}" == --* ]]; do
  case "$1" in
    --pose)
      POSE=true
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "ERROR: Unknown option: $1"
      usage
      exit 2
      ;;
  esac
done

if [[ $# -lt 1 ]]; then
  usage
  exit 2
fi

SOURCE="$1"
shift

if [[ $# -gt 0 ]]; then
  YOLO_MODEL="$1"
  shift
else
  YOLO_MODEL="$([[ "$POSE" == true ]] && echo "${POSE_MODEL}" || echo "yolo11n.pt")"
fi

if [[ $# -gt 0 ]]; then
  echo "ERROR: unexpected arguments: $*"
  usage
  exit 2
fi

PROJECT="${PROJECT:-runs}"
NAME="${NAME:-predict}"
OUT="${OUT:-$(basename "${SOURCE%.*}")_yolo11.mp4}"
BATCH="${BATCH:-16}"
DEVICE="${DEVICE:-0}"
COORDS="${COORDS:-${OUT%.*}_coords.txt}"

if [[ ! -f "$SOURCE" ]]; then
  echo "ERROR: input video not found: $SOURCE"
  exit 1
fi

if [[ -z "${SKIP_INSTALL:-}" ]]; then
  echo "[1/3] Installing OS deps (ffmpeg + OpenCV runtime libs)..."
  apt-get update -y
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ffmpeg \
    libgl1 \
    libglib2.0-0 \
    ca-certificates
  rm -rf /var/lib/apt/lists/*

  echo "[2/3] Installing Python deps (Ultralytics YOLO)..."
  python -m pip install --upgrade pip
  python -m pip install "numpy<2" ultralytics opencv-python
else
  echo "[1/3] Skipping OS/Python installs (already baked into the container image)."
  echo "[2/3] Dependency step skipped since SKIP_INSTALL=1."
fi

echo "[3/3] Running YOLO predict with GPU-friendly batch size..."
SOURCE="$SOURCE" YOLO_MODEL="$YOLO_MODEL" PROJECT="$PROJECT" NAME="$NAME" OUT="$OUT" \
BATCH="$BATCH" DEVICE="$DEVICE" COORDS="$COORDS" \
python - <<'PY'
import os
from pathlib import Path
from ultralytics import YOLO

source = os.environ["SOURCE"]
model_name = os.environ["YOLO_MODEL"]
project = os.environ["PROJECT"]
name = os.environ["NAME"]
out_name = os.environ["OUT"]
batch_size = int(os.environ["BATCH"])
device = os.environ["DEVICE"]
coords_path = Path(os.environ["COORDS"])

print(f"Model:  {model_name}")
print(f"Source: {source}")
print(f"Device: {device} (batch={batch_size})")

model = YOLO(model_name)

results = list(
    model.predict(
        source=source,
        project=project,
        name=name,
        device=device,
        batch=batch_size,
        save=True,
        save_txt=True,
        stream=True,
        exist_ok=True,
    )
)

if not results:
    raise SystemExit("No results returned by the YOLO model.")

save_dir = Path(results[0].save_dir)
src_video = save_dir / Path(source).name

if not src_video.exists():
    mp4s = sorted(save_dir.glob("*.mp4"))
    if mp4s:
        src_video = mp4s[-1]

if not src_video.exists():
    print(f"WARNING: Could not find output video in: {save_dir}")
    print("         Skipping video copy, but coordinates will still be saved.")
    video_saved = False
else:
    dst_video = Path(out_name)
    dst_video.write_bytes(src_video.read_bytes())
    video_saved = True

coords_path.parent.mkdir(parents=True, exist_ok=True)
names = model.names
with coords_path.open("w", encoding="utf-8") as coords_file:
    coords_file.write("# frame\tclass\tconfidence\tx1\ty1\tx2\ty2\n")
    for frame_index, result in enumerate(results):
        boxes = getattr(result, "boxes", None)
        if boxes is None or boxes.xyxy is None:
            continue
        coords_list = boxes.xyxy.cpu().tolist()
        confs = (
            boxes.conf.cpu().tolist()
            if getattr(boxes, "conf", None) is not None
            else [None] * len(coords_list)
        )
        classes = (
            boxes.cls.cpu().tolist()
            if getattr(boxes, "cls", None) is not None
            else [None] * len(coords_list)
        )
        for detection_index, (coords, confidence, cls_idx) in enumerate(
            zip(coords_list, confs, classes)
        ):
            class_name = (
                names.get(int(cls_idx), str(cls_idx))
                if cls_idx is not None
                else "unknown"
            )
            confidence_str = f"{confidence:.4f}" if confidence is not None else "None"
            coords_file.write(
                f"{frame_index}\t{class_name}\t{confidence_str}\t"
                f"{coords[0]:.2f}\t{coords[1]:.2f}\t{coords[2]:.2f}\t{coords[3]:.2f}\n"
            )

if video_saved:
    print(f"\n✅ Saved annotated video: {dst_video.resolve()}")
    print(f"   (Ultralytics run dir: {save_dir})")
else:
    print(f"\n⚠️  No video output was generated by YOLO")
    print(f"   (Ultralytics run dir: {save_dir})")
print(f"✅ Saved detection coords: {coords_path.resolve()}")
PY
